---
- name: List Power Virtual Server Cloud Images
  hosts: localhost
  collections:
   - ibmcloud.ibmcollection
  vars:
    pi_cloud_instance_id: "4a6dxxxx"

  tasks:
    - ibm_pi_images_info:
        pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"
        ibmcloud_api_key: "xxxxxx"
      register: images_list

    - debug:
        var: images_list.resource.image_info |
             items2dict(key_name='name', value_name='id')
